Resources:
  DoctorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Doctors
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: cpf
          AttributeType: S
        - AttributeName: especialidade_id
          AttributeType: S
        - AttributeName: distancia
          AttributeType: N
        - AttributeName: avaliacao
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CpfIndex
          KeySchema:
            - AttributeName: cpf
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: EspecialidadeIndex
          KeySchema:
            - AttributeName: especialidade_id
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: AvaliacaoIndex
          KeySchema:
            - AttributeName: avaliacao
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: DistanciaIndex
          KeySchema:
            - AttributeName: distancia
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  PacientesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Pacientes
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: cpf
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CpfIndex
          KeySchema:
            - AttributeName: cpf
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  ProntuariosTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'Prontuarios'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'id_paciente'
          AttributeType: 'S'
        - AttributeName: 'id_medico'
          AttributeType: 'S'
        # - AttributeName: 'consulta_data'
        #   AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'  # Partition key
      GlobalSecondaryIndexes:
        - IndexName: 'PacienteIndex'
          KeySchema:
            - AttributeName: 'id_paciente'
              KeyType: 'HASH'  # Partition key for index
            # - AttributeName: 'consulta_data'
            #   KeyType: 'RANGE'  # Sort key for index
          Projection:
            ProjectionType: 'ALL'
        - IndexName: 'MedicoIndex'
          KeySchema:
            - AttributeName: 'id_medico'
              KeyType: 'HASH'  # Partition key for index
            # - AttributeName: 'consulta_data'
            #   KeyType: 'RANGE'  # Sort key for index
          Projection:
            ProjectionType: 'ALL'
      BillingMode: PAY_PER_REQUEST

  DefaultRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${file(serverless.yml):service}-${file(serverless.yml):provider.stage}-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${file(serverless.yml):service}-${file(serverless.yml):provider.stage}-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource:
                  - !GetAtt DoctorsTable.Arn
                  - !GetAtt PacientesTable.Arn
                  - !GetAtt ProntuariosTable.Arn
                  - !Sub "${ProntuariosTable.Arn}/index/*"
