Resources:
  DoctorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Doctors
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: cpf
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CpfIndex
          KeySchema:
            - AttributeName: cpf
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  DefaultRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${file(serverless.yml):service}-${file(serverless.yml):provider.stage}-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${file(serverless.yml):service}-${file(serverless.yml):provider.stage}-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - '*'