service: hackaton-medicine-service
provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, "dev"}
  region: us-east-1
  environment: ${file(environment.yml)}
  iam:
    role: DefaultRole
  # ecr: ${file(src/api/handlers/images.yml)}

functions:
  - ${file(src/api/handlers/functions.yml)}

resources:
  - ${file(resources.yml)}

custom:
  doctorsTableArn:
    Fn::GetAtt:
      - DoctorsTable
      - Arn
  pythonRequirements:
    dockerizePip: true

package:
  patterns:
    - '!.git/**'
    - '!.github/**'
    - '!.ipynb_checkpoints/**'
    - '!services/*.ipynb'
    - '!.pytest_cache/**'
    - '!.vscode/**'
    - '!node_modules/**'
    - '!package.json'
    - '!package-lock.json'
plugins:
  - serverless-python-requirements
